---

gitlab_version: "8.0.5"

# The hostname passed as an envirnment variable into the container
gitlab_ip_addr: '127.0.0.1'
gitlab_hostname: git.example.com
gitlab_port_args: 
    - 80
    - 443
    - 22

# database usernames and passwords
gitlab_db_user: novatech

# must pass in the following variables
# gitlab_db_password: ''

# the name of the image being duilt and used for the container
gitlab_image_repo: 'https://github.com/novatechweb/docker-gitlab.git'
gitlab_image_tag: '{{gitlab_version}}'
gitlab_image_name: 'sameersbn/gitlab:{{gitlab_image_tag}}'
gitlab_db_image_name: 'postgres'
gitlab_db_image_tag: '9.4'
redis_image_name: 'redis'
redis_image_tag: '3.0'

# the name of the gitlab container
gitlab_container_name: '{{ docker_name_prefix }}gitlab'

# the name of the redis container for gitlab
gitlab_redis_container_name: '{{ docker_name_prefix }}gitlab-redis'

# the name of the postgres container for gitlab
gitlab_db_container_name: '{{ docker_name_prefix }}gitlab-db'

# the name of the data-volume used by the container
gitlab_dv_name: '{{ docker_name_prefix }}gitlab_DV'

# the name of the data-volume used by the postgres container
gitlab_db_dv_name: '{{ docker_name_prefix }}gitlab_db_DV'

# restore directories to temporarly store data being restored into docker containers
gitlab_docker_backup_dir: '{{ docker_backup_dir }}/GIT'
gitlab_docker_restore_dir: '{{ bacula_dest }}{{ gitlab_docker_backup_dir }}'

# Network names
docker_network_frontend: 'frontend'
