---

container_addr_map:
  svn:
    ip_addr: 172.16.0.201
    hostname: svn.novatech-llc.com
  git:
    ip_addr: 172.16.0.202
    hostname: git.novatech-llc.com
  wiki:
    ip_addr: 172.16.0.203
    hostname: wiki.novatech-llc.com
  mantisbt:
    ip_addr: 172.16.0.204
    hostname: mantis.novatech-llc.com
  build:
    ip_addr: 172.16.0.205
    hostname: buildsystem.novatech-llc.com
  testssh:
    ip_addr: 172.16.0.206
    hostname: testssh.novatech-llc.com
  exim4:
    ip_addr: 172.16.0.207
    hostname: mail.novatech-llc.com
  ldap:
    ip_addr: 172.16.0.208
    hostname: ldap.novatech-llc.com
  phpldapadmin:
    ip_addr: 172.16.0.208
    hostname: ldap.novatech-llc.com
  phpmyadmin:
    ip_addr: 172.16.0.209
    hostname: phpmyadmin.novatech-llc.com
  buildbot:
    ip_addr: 172.16.0.210
    hostname: buildbot.novatech-llc.com
