---

svn_hostname: svn.novatech-llc.com
svn_port_args: []

gitlab_hostname: git.novatech-llc.com
gitlab_port_args:
- "{{ gitlab_ip_addr }}:22:22"

wiki_hostname: wiki.novatech-llc.com
wiki_port_args: []

mantisbt_hostname: mantis.novatech-llc.com
mantisbt_port_args: []

build_hostname: buildsystem.novatech-llc.com
build_port_args: []

testssh_hostname: testssh.novatech-llc.com
testssh_port_args:
- "{{ testssh_ip_addr }}:2200:22"

exim4_hostname: mail.novatech-llc.com
exim4_port_args:
- "{{ ansible_facts.default_ipv4.address }}:25:25"
- "{{ ansible_facts.default_ipv4.address }}:465:465"
- "{{ ansible_facts.default_ipv4.address }}:587:587"

openldap_hostname: ldap.novatech-llc.com
openldap_port_args:
- "{{ ansible_facts.default_ipv4.address }}:389:389"
- "{{ ansible_facts.default_ipv4.address }}:636:636"

phpldapadmin_hostname: ldap.novatech-llc.com
phpldapadmin_port_args: []

phpmyadmin_hostname: phpmyadmin.novatech-llc.com

buildbot_hostname: buildbot.novatech-llc.com
buildbot_port_args:
- "{{ ansible_facts.default_ipv4.address }}:9989:9989"

nexus_hostname: nexus.novatech-llc.com
nexus_port_args: []

haproxy_port_args:
- "{{ ansible_facts.default_ipv4.address }}:80:80"
- "{{ ansible_facts.default_ipv4.address }}:443:443"
- "{{ ansible_facts.default_ipv4.address }}:9000:9000"
