---
# This playbook deploys the whole application stack in this site.

- name: Dump Variables
  hosts: all
  tags:
  - debugging
  tasks:
  - template:
      src: templates/dump_variables
      dest: /tmp/ansible_variables
  - fetch:
      src: /tmp/ansible_variables
      dest: "{{inventory_hostname}}_ansible_variables"

- name: Bacula
  hosts: bacula
  remote_user: ansibleremote
  become: true
  become_user: root
  become_method: sudo
  roles:
  - role: mariadb
    mariadb_open_firewall: true
    mariadb_remote_root_access: false
  - role: bacula-director
  - role: bacula-storage
    tags:
    - bacula_storage
  - role: bacula-client
  - role: bacula-console
  - role: bacula-script
    assemble_scripts: false
  # - role: bacula-catalog

- name: Prepare Docker host systems
  hosts: docker-hosts
  remote_user: ansibleremote
  become: true
  become_user: root
  become_method: sudo
  roles:
  - name: Setup SSH Daemon
    role: sshd
    tags:
    - sshd
  - name: Run common Docker tasks
    role: docker-common
    tags:
    - docker_common

- name: Install/Setup Docker images and containers on daedalus
  hosts: daedalus
  remote_user: ansibleremote
  become: true
  become_user: root
  become_method: sudo
  roles:
  - name: Run bacula-restores symlinks
    role: bacula-restores
    tags:
    - bacula_restores
  - name: Configure Docker networking
    role: docker-networking
    connection: '{{ daedalus_net_connection }}'
    subnet: '{{ daedalus_subnet }}'
    services:
    - svn
    - openldap
    - exim4
    - gitlab
    - wiki
    - mantisbt
    - build
    - testssh
    - buildbot
    tags:
    - docker_networking
  - name: Build the openssl Docker volume
    role: docker-openssl
    tags:
    - openssl_container
  - name: Build and start the SVN Docker container
    role: docker-svn
    svn_repos: 'ddio NCD_Release'
    tags:
    - svn_container
  - name: Build and start the openldap Docker container
    role: docker-openldap
    tags:
    - openldap_container
  - name: Build and start the exim4 Docker container
    role: docker-exim4
    tags:
    - exim4_container
  - name: Build and start the GitLab Docker container
    role: docker-gitlab
    gitlab_db_user: novatech
    tags:
    - gitlab_container
  - name: Build and start the MediaWIKI Docker container
    role: docker-mediawiki
    wiki_db_user: novatech
    tags:
    - wiki_container
  - name: Build and start the MantisBT Docker container
    role: docker-mantisbt
    tags:
    - mantisbt_container
  - name: Build and start Build System (Test Station) containers
    role: docker-buildsystem
    tags:
    - buildsystem_container

- name: Setup the Build System (Test Station) with repo data
  hosts: buildsystem
  roles:
  - role: buildsystem
    tags:
    - buildsystem_container

- name: Assemble Bacula backup scripts
  hosts: bacula
  remote_user: ansibleremote
  become: true
  become_user: root
  become_method: sudo
  roles:
  - role: bacula-script
    assemble_scripts: true

- name: Cleanup tasks
  hosts: all
  remote_user: ansibleremote
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: Copy credentials to the /etc dir
    copy:
      src: "{{ playbook_dir }}/credentials/"
      dest: /etc/ansible-credentials/
      owner: root
      group: root
      mode: 'u=rw,g=,o='
  - name: set directory permissions for /etc/ansible-credentials/
    file:
      state: directory
      path: /etc/ansible-credentials/
      owner: root
      group: root
      mode: 'u=rw,g=,o='
      recurse: yes
  - name: Remove bacula-restores dir
    file:
      path: /tmp/bacula-restores/
      state: absent
